api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    path("",views.ListItemAPIView.as_view(),name="item-list"),
    path("create/", views.CreateItemAPIView.as_view(),name="item-create"),
    path("update/<int:pk>/",views.UpdateItemAPIView.as_view(),name="update-item"),
    path("delete/<int:pk>/",views.DeleteItemAPIView.as_view(),name="delete-item"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Items.urls')),
    path('api/',include('api.urls')),
    path('users/', include('users.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from users.views import SignUpView, LoginPageView, log_out,profile,ProfileView, verify_code
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
    path('login/', LoginPageView.as_view(), name="login"),
    path('profile_update/', profile, name= 'profile-update'),
    path('profile/', login_required(ProfileView.as_view()), name="profile"),
    path('logout/', log_out, name="logout"),
    path('verify/', views.verify_code, name="verify"),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from PIL import Image
# Create your models here.

class Person(AbstractUser):
    phone =models.TextField(max_length=20, blank=False)
    is_verified = models.BooleanField(default=False)

class Profile(models.Model):
    user = models.OneToOneField(Person, on_delete=models.CASCADE)
    bio = models.TextField()
    image = models.ImageField(default='images/Avatar.png', upload_to='images')
    

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from users.models import Person, Profile
from django.contrib.auth import get_user_model
User = get_user_model()

class UserRegisterForm(BaseUserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')
    phone = forms.CharField(max_length=20, required=True, help_text='Phone number that will receive OTP')

    class Meta:
        model = Person
        fields = ('username', 'email','phone','password1', 'password2', )


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Person
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    

    class Meta: 
        model = Profile
        fields = ['image', 'bio']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)
    

class VerifyForm(forms.Form):
    code = forms.CharField(max_length=8, required=True, help_text='Enter Code')

users/views.py
from tempfile import template
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from users.forms import  LoginForm, UserRegisterForm, ProfileUpdateForm, UserUpdateForm, VerifyForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from django.views.generic import CreateView, UpdateView, TemplateView, View, DetailView
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import login, authenticate, logout
from django.template import RequestContext
from django.contrib.auth import get_user_model
from users.models import Profile
from django.urls import reverse
from users import verify
# Create your views here.

User = get_user_model()

class SignUpView(View):
    form_class =  UserRegisterForm
    success_url = reverse_lazy("user:login")
    template_name = "signup.html"

    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})
        
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
            
        else:
            form = self.form_class
            message = 'Incorrect Credentials!Please Try again'
        return render(request, self.template_name, context={'form': form, 'message': message})




@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile) 
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('user:profile') # Redirect back to profile page

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'profile_update.html', context)

class ProfileView(TemplateView):
    template_name = "profile.html"


class LoginPageView(View):
    template_name = 'login.html'
    form_class = LoginForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})
        
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                phone = verify.send(form.cleaned_data.get('phone'))
            )
            
            if user is not None:
                login(request, user)
                return redirect('item:item-list')
        message = 'Incorrect Credentials!Please Try again'
        return render(request, self.template_name, context={'form': form, 'message': message})

@login_required
def verify_code(request):
    if request.method == 'POST':
        form = VerifyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('code')
            if verify.check(request.user.phone, code):
                request.user.is_verified = True
                request.user.save()
                return redirect('index')
    
    else:
        form = VerifyForm()
    return render(request, 'verify.html', {'form': form})




def log_out(request):
    logout(request)
    return redirect(reverse('user:login'))

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"
    rel="stylesheet"
    />
    <link href="static/admin/css/style.css" rel="stylesheet">
    <title></title>
</head>
<body>
    <!-- {%  if user.is_authenticated %}
        <p>You are logged in as {{ request.user }}. Click here to <a href="{% url 'user:logout' %}">log out</a></p>
    {% endif %} -->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-2">ToDo App</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
            
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <!-- MDB -->
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"
    ></script>
</body>
</html>

users/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign In</p>
  
                  <form class="form-horizontal form" name="LoginForm"  method="post">
                    {% csrf_token %}
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="text" id="username" name="username"  placeholder="Username">

                        <label class="form-label" for="form3Example1c">Your Username</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>
<!-- 
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="text" id="phone" name="phone"  placeholder="Your phone number">
                        <label class="form-label" for="form3Example1">Your Phone Number</label>
                      </div>
                    </div> -->

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Login</button>
                    </div>
  
                  </form>
                  <p class="text-center">If you do not have an account, <a href="{% url 'user:signup' %}">register</a> instead.</p>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Profile Page{% endblock title %}

{% block content %} 
<section class="vh-100" style="background-color: #ececec;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0" style="background-color: #f6d365;">
            <div class="col-md-4 gradient-custom text-center"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              {% if user.profile.image %}
              <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="{{ user.username }}">
              {% else %}
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
              {% endif %}
              <h5>@ {{ user.username }}</h5>
              {% if user.profile.bio %}
                <p>{{ user.profile.bio }}</p>
              {% else %}
                <p>Click update to add a bio</p>
              {% endif %}  
              <a href="{% url 'user:profile-update' %}" class="btn btn-primary">Update profile</a>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>Information</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Email</h6>
                    <p class="text-muted">{{ user.email }}</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Phone</h6>
                    <p class="text-muted">123 456 789</p>
                  </div>
                </div>
                <h6>Recent To-Do List Items</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Add title</h6>
                    <p class="text-muted">Add Item</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Add date</h6>
                    <p class="text-muted">Dolor sit amet</p>
                  </div>
                </div>
                <div class="d-flex justify-content-start">
                  <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    


{% endblock%}

users/templates/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Profile Page{% endblock title %}

{% block content %} 
    
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="card col-lg-6 offset-lg-3 mb-3">
                <div class="row">
                 
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Profile Info</legend>
                            {{ u_form|crispy }} <!-- User form -->
                            {{ p_form|crispy }} <!-- Profile form -->
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock%}

users/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form method="POST" form="AdminUserForm" class="mx-1 mx-md-4">
                    {% csrf_token %}

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="text" id="username" name="username"  placeholder="Username">
                        <label class="form-label" for="form3Example1c">Your Username</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="email" id="email" name="email"  placeholder="Email address">
                        <label class="form-label" for="form3Example1">Your Email</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="text" id="phone" name="phone"  placeholder="Your phone number">
                        <label class="form-label" for="form3Example1">Your Phone Number</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="password" name="password1" id="password1" placeholder="Password">
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input class="form-control" type="password" name="password2" id="password2" placeholder="Password">
                        <label class="form-label" for="form3Example4cd">Repeat your password</label>
                      </div>
                    </div>
  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    </div>
  
                  </form>
                  <p class="text-center">If you already have an account, <a href="{% url 'user:login' %}">login</a> instead.</p>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

users/templates/verify.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="container d-flex align-items-center justify-content-center">
    <h1>Verify your account</h1>
</div>
<div class="container d-flex align-items-center justify-content-center">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Verify</button>
        <a href="#"><button type="button" class="btn btn-primary">Resend Code</button></a>

    </form>
</div>

{% endblock %}