Items/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from Items.views import ItemsCreateView, ItemsDeleteView,ItemsUpdateView,ItemsListView,ItemsDetailView

app_name = 'item'
urlpatterns = [
    path('', ItemsListView.as_view(), name='item-list'),
    path('create/', login_required(ItemsCreateView.as_view()), name='item-create'),
    path('delete/<int:pk>', login_required(ItemsDeleteView.as_view()), name='item-delete'),
    path('update/<int:pk>', login_required(ItemsUpdateView.as_view()), name='item-update'),
    path('detail/<int:pk>', login_required(ItemsDetailView.as_view()), name='item-detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    path("",views.ListItemAPIView.as_view(),name="item-list"),
    path("create/", views.CreateItemAPIView.as_view(),name="item-create"),
    path("update/<int:pk>/",views.UpdateItemAPIView.as_view(),name="update-item"),
    path("delete/<int:pk>/",views.DeleteItemAPIView.as_view(),name="delete-item"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Items.urls')),
    path('api/',include('api.urls')),
    path('users/', include('users.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from users.views import SignUpView, LoginPageView, log_out,profile,ProfileView, verify_code
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
    path('login/', LoginPageView.as_view(), name="login"),
    path('profile_update/', profile, name= 'profile-update'),
    path('profile/', login_required(ProfileView.as_view()), name="profile"),
    path('logout/', log_out, name="logout"),
    path('verify/', views.verify_code, name="verify"),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Items/models.py
from django.db import models

# Create your models here.
class Items(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    created_date = models.DateField(auto_now_add=True)
    deadline = models.DateField(auto_now_add=False)

    def __str__(self):
        return self.title

Items/views.py
from tempfile import template
from django.shortcuts import render
from django.urls import reverse_lazy
from Items.models import Items
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

class ItemsListView(ListView):
    model = Items
    paginate_by = 10
    ordering = ['-created_date']
    context_object_name = 'item'
    template_name = "items_list.html"


class ItemsCreateView(CreateView):
    model = Items
    fields = ['title', 'description', 'deadline']
    template_name = "items_create.html"
    success_url = reverse_lazy('item:item-list')
    


class ItemsDetailView(DetailView):
    model = Items
    template_name = 'items_detail.html'
    context_object_name = 'items'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(ItemsDetailView, self).get_context_data(**kwargs)
        context['items'] = Items.objects.all()
        return context

class ItemsUpdateView(UpdateView):
    model = Items
    fields = ['title', 'description', 'deadline']
    template_name = "items_update.html"
    success_url = reverse_lazy('item:item-list')

class ItemsDeleteView(DeleteView):
    model = Items
    template_name = "items_delete.html"
    success_url = reverse_lazy('item:item-list')

Items/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>ToDo</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              
             
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'item:item-list' %}">To Do List</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'item:item-create' %}">Create A New ToDo Item</a>
                </li>

             
              
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:signup' %}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'item:item-list' %}">To Do List</a>
                </li>
                </ul>
                <div class="collapse navbar-collapse justify-content-end">
                  <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a href="{% url 'user:login' %}" class="nav-link m-2 menu-item nav-active float-end">You are not logged in.</a>
                      </li>
                  </ul>
                </div>
             

          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

Items/templates/items_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="card text-center">
    <div class="card-header">
      Create a ToDo Item
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}

                {{ form.title|as_crispy_field }}
                {{ form.description|as_crispy_field }}
                {{ form.deadline|as_crispy_field }}
                  
            <br>
            <button type="submit" class="btn btn-primary" > Save Item</button>
        </form>
    </div>
</div>

{% endblock %}

Items/templates/items_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="card text-center">
    <div class="card-header">
      Delete a ToDo Item
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}

            <h1>Are you sure you want to delete "{{ object }}"?</h1>
             
            <br>
            <button type="submit" class="btn btn-danger" > Delete Item</button>
        </form>
    </div>
</div>

{% endblock %}

Items/templates/items_detail.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Created_date</th>
        <th scope="col">Deadline</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">#</th>
        <td>{{object.title}}</td>
        <td>{{object.description}}</td>
        <td>{{object.created_date}}</td>
        <td>{{object.deadline}}</td>
        <td><a href="{% url 'item:item-update' object.id %}"><button type="button" class="btn btn-secondary">Edit</button></a></td>
        <td><a href="{% url 'item:item-delete' object.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
        
       
      </tr>
    </tbody>
</table>
{% endblock %}

Items/templates/items_list.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<div class="card text-center">

  <div class="card-body">
    <a href="{% url 'item:item-create' %}" class="btn btn-primary">Create a new to-do list item</a>
  </div>
 
</div>
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Date created</th>
        <th scope="col">Deadline</th>
      </tr>
    </thead>
    <tbody>
        {% for object in item %}
            
                <tr>
                    <th scope="row">#</th>
                    <td><a href="{% url 'item:item-detail' object.id %}">{{object.title}}</a></td>
                    <td>{{object.description}}</td>
                    <td>{{object.created_date}}</td>
                    <td>{{object.deadline}}</td>
                
                </tr>
          
        {% empty %}
                <tr>
                    <th scope="row">#</th>
                    <td>No to do list created yet.</td>
                    <th scope="row">#</th>
                    <th scope="row">#</th>
                    <th scope="row">#</th>
                
                </tr>
        
        {% endfor %}
    </tbody>
</table>

{% endblock %}

Items/templates/items_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="card text-center">
    <div class="card-header">
      Edit a ToDo Item
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}

                {{ form.title|as_crispy_field }}
                {{ form.description|as_crispy_field }}
                {{ form.deadline|as_crispy_field }}
                  
            <br>
            <button type="submit" class="btn btn-primary" > Save Item</button>
        </form>
    </div>
</div>

{% endblock %}